name: digiepg update

on:
  schedule:
    # Her 30 dakikada bir çalışır.
    # Örnek: 00:00, 00:30, 01:00, 01:30 vb.
    - cron: '*/30 * * * *'
  # Manuel çalıştırma için
  workflow_dispatch:

permissions:
  contents: write

jobs:
  epg-update:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonla
        # Depoyu çalışma dizinine klonlar.
        uses: actions/checkout@v4

      - name: Python kurulumu
        # Python 3.x sürümünü kurar.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Bağımlılıkları yükle
        # Gerekli Python kütüphanelerini yükler.
        # requests ve beautifulsoup4 kütüphaneleri aynı anda yüklenir.
        run: |
          pip install requests beautifulsoup4

      - name: EPG Verisini Güncelle
        # digiepg.py betiğini çalıştırır.
        # Çalışma dizinindeki dosyaları listeler (hata ayıklama için faydalı).
        run: |
          python digiepg.py
          ls -lah

      - name: Commit & Push
        # Değişiklikleri Git deposuna kaydeder ve ana dala (main branch) gönderir.
        run: |
          # Git kullanıcı adı ve e-posta ayarlarını yapar.
          git config --global user.name "epg-bot"
          git config --global user.email "epg@bot.com"
          
          # digiepg.xml dosyasını staging alanına ekler.
          # Dosya yoksa uyarı verir ve işlemeye devam eder.
          git add digiepg.xml || echo "digiepg.xml dosyası bulunamadı veya eklenemedi."
          
          # Değişiklikleri commit eder.
          # Değişiklik yoksa uyarı verir ve işlemeye devam eder.
          git commit -m "🔄 EPG otomatik güncellendi" || echo "Yapılacak bir değişiklik yok."
          
          # Değişiklikleri origin/main'e push eder.
          # Push başarısız olursa uyarı verir ve işlemeye devam eder.
          git push origin main || echo "Push işlemi başarısız oldu veya gerekli değildi."
