name: Digi php EPG Güncelleme

on:
  schedule:
    # Her 30 dakikada bir çalışır.
    # Örnek: 00:00, 00:30, 01:00, 01:30 vb.
    - cron: '*/30 * * * *'
  # İş akışını manuel olarak tetiklemek için
  workflow_dispatch:

permissions:
  contents: write # Depoya yazma izni verir

jobs:
  epg-update:
    runs-on: ubuntu-latest # İş akışı için Ubuntu işletim sistemi kullanır

    steps:
      - name: Depoyu Klonla
        # Mevcut depoyu runner'a klonlar.
        uses: actions/checkout@v4

      - name: PHP Kurulumu
        # PHP ortamını kurar. PHP sürümünü belirtebilirsiniz (örneğin '8.x').
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.x' # PHP sürümünüzü buraya yazın (örn. '7.4', '8.0', '8.1', '8.2', '8.3')
          extensions: curl, dom, xml # cURL, DOM ve XML uzantılarını etkinleştirir

      - name: EPG PHP Betiğini Çalıştır
        # Digitürkepg.php betiğini çalıştırır.
        # Betiğin çıktı olarak bir epg.xml dosyası oluşturduğunu varsayarız.
        run: |
          php Digitürkepg.php
          ls -lah # Hata ayıklama için oluşturulan dosyaları listeler

      - name: Değişiklikleri Kaydet ve Push Et
        # Oluşturulan epg.xml dosyasını Git deposuna kaydeder ve geri yükler.
        run: |
          git config --global user.name "github-actions[bot]" # Git commit için kullanıcı adı ayarlar
          git config --global user.email "github-actions[bot]@users.noreply.github.com" # Git commit için e-posta ayarlar
          
          git add digiphpepg.xml || echo "epg.xml dosyası bulunamadı veya eklenemedi." # epg.xml dosyasını ekler
          
          # Yalnızca değişiklik varsa commit yapar.
          git commit -m "🔄 EPG otomatik güncellendi (PHP)" || echo "Yapılacak bir değişiklik yok."
          
          git push origin main || echo "Push işlemi başarısız oldu veya gerekli değildi." # Değişiklikleri main dalına gönderir
