name: EPG 

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  m3u-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonla
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerekli modüller
        run: pip install requests

      - name: EPG eşle
        run: python epg_matcher.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add m3u-epg.m3u || echo "Dosya yok"
          git commit -m "🔄 EPG uyumlu m3u güncellendi" || echo "Değişiklik yok"
          git push origin main || echo "Push yok"
